name: brokr
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+5

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  get: 4.6.5
  font_awesome_flutter: 10.3.0
  image_picker: 0.8.6
  dotted_border: 2.0.0+3
  flutter_expanded_tile: 0.3.6
  rxdart: 0.27.7
  google_maps_flutter: 2.2.2
  geolocator: 9.0.2
  animate_do: 3.0.2
  flutter_keyboard_visibility: 5.4.0
  camera: ^0.10.0+4
  google_mlkit_text_recognition: ^0.4.0
  permission_handler: ^10.2.0
  http:
  barcode_scan2:
  flutter_mobile_vision_2:

  flutter_settings_screens: ^0.3.3-null-safety+2
  shared_preferences: ^2.0.15
  lottie: ^2.2.0
  flutter_spinkit: ^5.1.0
  animated: ^2.0.0
  country_picker: ^2.0.19
  mask_text_input_formatter: ^2.4.0
  flutter_svg: ^1.1.6
  grouped_list: ^5.1.2
  intl: ^0.18.0
  share_plus: ^6.3.1
  custom_navigation_bar: ^0.8.2
  pinput: ^2.2.21
  iconsax: ^0.0.8
  equatable: ^2.0.5
  table_calendar: ^3.0.9
  cached_network_image: ^3.2.3
  custom_map_markers: ^0.0.2+1
  card_loading: ^0.2.2
  flutter_calendar_carousel: ^2.4.2
  calendar_date_picker2: ^0.5.2
  url_launcher: ^6.1.7
  syncfusion_flutter_sliders: ^20.2.36
  paged_vertical_calendar: ^1.1.6
  syncfusion_flutter_charts: ^20.2.36
  syncfusion_flutter_core: ^20.4.54
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.7.0
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.0

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/logo/iosICON.png"

dependecy_overrides:
 modal_bottom_sheet:
     git:
       url: https://github.com/followthemoney1/modal_bottom_sheet.git
       ref: main
       path: modal_bottom_sheet  

flutter:

  uses-material-design: true

  assets:
    - assets/listing/
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/lottie/
    - assets/bottombar/
    - assets/carfeatures/
    - assets/housefeatures/
    - assets/stayfeatures/
    - assets/stayfilters/
    - assets/yacthfeatures/
    - assets/boatfeatures/
    - assets/amenities_stay/
    - assets/specifications_yacht/
    - assets/specifications_boats/
    - assets/features_yatch/

  fonts:
  - family: Overpass
    fonts:
    - asset: fonts/Overpass-VariableFont_wght.ttf

  - family: Inter-Bold
    fonts:
    - asset: fonts/Inter-Bold.ttf
  - family: Inter-Black
    fonts:
    - asset: fonts/Inter-Black.ttf
  - family: Inter-Medium
    fonts:
    - asset: fonts/Inter-Medium.ttf
  - family: Inter-Regular
    fonts:
    - asset: fonts/Inter-Regular.ttf


  - family: Poppins-Black
    fonts:
    - asset: fonts/Poppins-Black.ttf
  - family: Poppins-Medium
    fonts:
    - asset: fonts/Poppins-Medium.ttf
  - family: Poppins-Regular
    fonts:
    - asset: fonts/Poppins-Regular.ttf
  - family: Poppins-Bold

    fonts:
    - asset: fonts/TTFors-Bold.ttf
  - family: TTFors-Black
    fonts:
    - asset: fonts/TTFors-Black.ttf
  - family: TTFors-Medium
    fonts:
    - asset: fonts/TTFors-Medium.ttf
  - family: TTFors-Regular
    fonts:
    - asset: fonts/TTFors-Regular.ttf    
