class ListUtilFilter {
  static List<String> sortby = [
    "All",
    "Relevance",
    "Price High",
    "Price Low",
  ];
  static List<String> makes = [
    "All Makes",
    "AM General",
    "Acura",
    "Alfa-Romeo",
    "Aston Martin",
    "Audi",
    "BMW",
    "Bentley",
    "Buick",
    "Cadillac",
    "Can-Am",
    "Chevrolet",
    "Chrysler",
    "Delorean",
    "Dodge",
    "Ferrari",
    "Fiat",
    "Fisker",
    "Ford",
    "Freightliner",
    "GMC",
    "Genesis",
    "Honda",
    "Hummer",
    "Hyundai",
    "Infiniti",
    "Jaguar",
    "Jeep",
    "Karma",
    "Kia",
    "Lamborghini",
    "Lancia",
    "Land Rover",
    "Lexus",
    "Lincoln",
    "Lotus",
    "Lucid",
    "Maserati",
    "Mazda",
    "Mclaren",
    "Mercedes-Benz",
    "Mercury",
    "Mini",
    "Mitsubishi",
    "Nissan",
    "Oldsmobile",
    "Plymouth",
    "olaris",
    "Polestar",
    "Pontiac",
    "Porsche",
    "Ram",
    "Rivian",
    "Rolls-Royce",
    "Saab"
        "Saturn",
    "Scion",
    "Smart",
    "Subaru",
    "Suzuki",
    "Tesla",
    "Toyota",
    "Vanderhall",
    "Vinfast",
    "Volkswagen",
    "Volvo",
  ];

  static List<String> years = [
    "All Years",
    "1950",
    "1951",
    "1952",
    "1953",
    "1954",
    "1955",
    "1956",
    "1957",
    "1958",
    "1959",
    "1960",
    "1961",
    "1962",
    "1963",
    "1964",
    "1965",
    "1966",
    "1967",
    "1968",
    "1969",
    "1970",
    "1971",
    "1972",
    "1973",
    "1974",
    "1975",
    "1976",
    "1977",
    "1978",
    "1979",
    "1980",
    "1981",
    "1982",
    "1983",
    "1984",
    "1985",
    "1986",
    "1987",
    "1988",
    "1989",
    "1990",
    "1991",
    "1992",
    "1993",
    "1994",
    "1995",
    "1996",
    "1997",
    "1998",
    "1999",
    "2000",
    "2001",
    "2002",
    "2003",
    "2004",
    "2005",
    "2006",
    "2007",
    "2008",
    "2009",
    "2010",
    "2011",
    "2012",
    "2013",
    "2014",
    "2015",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023",
    "2024",
  ];

  static List<String> seats = [
    "All Seats",
    "2 Or More",
    "3 Or More",
    "4 Or More",
    "5 Or More",
    "6 Or More",
  ];

  static List<String> vehicleType = [
    "All Types",
    "Cars",
    "SUVs",
    "Minivans",
    "Trucks",
    "Vans"
  ];

  static List<String> boatsType = [
    "All Types",
    "Power",
    "Sail",
  ];

  static List<String> lengthBoats = [
    "All Lenght",
    "0ft",
    "1ft",
    "2ft",
    "3ft",
    "4ft",
    "5ft",
    "6ft",
    "7ft",
    "8ft",
    "9ft",
    "10ft",
    "11ft",
    "12ft",
    "13ft",
    "14ft",
    "15ft",
    "16ft",
    "17ft",
    "18ft",
    "19ft",
    "20ft",
    "21ft",
    "22ft",
    "23ft",
    "24ft",
    "25ft",
    "26ft",
    "27ft",
    "28ft",
    "29ft",
    "30ft",
    "31ft",
    "32ft",
    "33ft",
    "34ft",
    "35ft",
    "36ft",
    "37ft",
    "38ft",
    "39ft",
    "40ft",
    "41ft",
    "42ft",
    "43ft",
    "44ft",
    "45ft",
    "46ft",
    "47ft",
    "48ft",
    "49ft",
    "50ft",
    "51ft",
    "52ft",
    "53ft",
    "54ft",
    "55ft",
    "56ft",
    "57ft",
    "58ft",
    "59ft",
    "60ft",
    "61ft",
    "62ft",
    "63ft",
    "64ft",
    "65ft",
    "66ft",
    "67ft",
    "68ft",
    "69ft",
    "70ft",
    "71ft",
    "72ft",
    "73ft",
    "74ft",
    "75ft",
  ];
  static List<String> makesBoats = [
    "All Makes",
    "3D TENDER",
    "ABATE",
    "ABSOLUTE YACHTS",
    "AB YACHTS",
    "ACM",
    "ACQUAVIVA",
    "ADVENTURE",
    "AICON",
    "AIRON MARINE",
    "ALALUNGA",
    "ALBIN MARINE",
    "ALFASTREET MARINE",
    "ALLIAURA MARINE",
    "ALOA",
    "ALPA",
    "ALTAMAREA",
    "ALUBAT",
    "ALUMARINE",
    "AMEL",
    "APREAMARE",
    "AQUADOR",
    "AQUANAUT",
    "AQUILA YACHTS",
    "ARCHAMBAULT",
    "ARCOA",
    "ARIMAR",
    "ARNO",
    "ARVOR",
    "AS MARINE",
    "ASTINOR",
    "ASTONDOA",
    "ATLANTIC",
    "ATLANTIC MARINE",
    "AUBIN",
    "AUSTIN PARKER",
    "AVAR YACHT",
    "AVON",
    "AXOPAR",
    "AZIMUT",
    "B2 MARINE",
    "BAGLIETTO",
    "BAIA",
    "BAJA",
    "BALI CATAMARANS",
    "BALTIC YACHTS",
    "BARBERIS",
    "BATTIFERO",
    "BAVARIA",
    "BAYLINER",
    "BELLIURE",
    "BENETEAU",
    "BENETTI",
    "BERTRAM",
    "BIRCHWOOD",
    "BLACK PEPPER",
    "BLU MARTIN",
    "BMA BOATS",
    "BODRUM YACHTS",
    "BOESCH",
    "BOLERO",
    "BOMBARD",
    "BOSTON WHALER",
    "BRIG",
    "BROOM",
    "BRUCE ROBERTS",
    "BRUNO ABBATE",
    "BSC",
    "BUSTER",
    "BWA",
    "CAICCO",
    "CAMPER AND NICHOLSON",
    "CAMPION",
    "CAMUFFO",
    "CANADOS",
    "CANTIERE AZZURRO",
    "CANTIERI DI DONNA",
    "CANTIERI DI PISA",
    "CAPELLI",
    "CARNEVALI",
    "CARTER BOATS",
    "CARVER YACHTS",
    "CATALINA YACHTS",
    "CATANA",
    "CATARSI",
    "CAYMAN YACHTS",
    "C CATAMARANS",
    "CHANTIER BERTIN",
    "CHAPARRAL",
    "CHASSIRON",
    "CHEOY LEE",
    "CHRIS CRAFT",
    "CIGARETTE",
    "CNB",
    "CNSO",
    "COBALT MARINE",
    "COLOMBO",
    "COLVIC",
    "COLVIC CRAFT",
    "COMAR",
    "COMITTI",
    "CONAM",
    "CONTESSA YACHTS",
    "CONTEST YACHTS",
    "CORMORANT",
    "CORNISH CRABBER",
    "CRANCHI",
    "CRESTITALIA",
    "CRN",
    "CROWNLINE",
    "CRUISERS YACHTS",
    "CURSUS VOILE ET PATRIMOINE",
    "DALLA PIETA",
    "DEAN",
    "DE ANTONIO",
    "DEHLER",
    "DELPHIA YACHTS",
    "DELTA",
    "DELTA MARINE",
    "DIPOL",
    "DOMINATOR",
    "DORAL",
    "DRAGO",
    "DUFOUR",
    "EDEL",
    "EDGE WATER",
    "EIDER MARINE",
    "ELAN",
    "ENTERPRISE MARINE",
    "EOLO",
    "ESTENSI",
    "ETAP YACHTING",
    "ETCHELLS",
    "EUROBANKER",
    "EXCEL",
    "EXCESS",
    "EXPRESSION",
    "FAETON",
    "FAIRLINE",
    "FALCON",
    "FARR YACHT DESIGN",
    "FASHION YACHTS",
    "FERRETTI",
    "FIART MARE",
    "FIBRAMAR",
    "FIM",
    "FINNMASTER",
    "FIPA ITALIANA YACHTS",
    "FISHER YACHTS",
    "FJORD",
    "FORMULA",
    "FOUNTAINE PAJOT",
    "FOUR WINNS",
    "FRANCHINI",
    "FRANS MAAS",
    "FRATELLI APREA",
    "FUN YAK",
    "GALEON",
    "GALIA",
    "GALLART",
    "GEMINI YACHTS",
    "GIANETTI YACHT",
    "GIORGI",
    "GLASTRON",
    "GOBBI",
    "GOZZO POSITANO",
    "GRADY WHITE",
    "GRAND",
    "GRAND BANKS",
    "GRAND SOLEIL",
    "GREENLINE",
    "GULF CRAFT",
    "GUY COUACH",
    "GUY MARINE",
    "HALLBERG RASSY",
    "HANSE YACHTS",
    "HARDY MARINE",
    "HATTERAS",
    "HEAVEN",
    "HEYDAY",
    "HIGHFIELD",
    "HILLYARD",
    "HONDA",
    "HUNTER",
    "HYLAS YACHTS",
    "ILVER",
    "INNOVAZIONE E PROGETTI",
    "INTERMARE",
    "INVICTUS",
    "ISLAND GIPSY",
    "ISLAND PACKET",
    "ITALCRAFT",
    "ITALIA YACHTS",
    "ITALMAR",
    "ITAMA",
    "JAGUAR",
    "J BOATS",
    "J COMPOSITES",
    "JEANNEAU",
    "JOEMARIN",
    "JOHNSON",
    "JOKER BOAT",
    "JONGERT",
    "JUDEL AND VROJLIK",
    "KARNIC",
    "KELT",
    "KHA SHING",
    "KIRIE",
    "KOLIBRI",
    "KOLMARINE",
    "LAGOON",
    "LARSON",
    "LATITUDE 46",
    "LE BOAT",
    "LEISURE",
    "LEMA",
    "LINDER",
    "LINSSEN",
    "LM",
    "LOMAC",
    "LUHRS",
    "MAC GREGOR",
    "MAGAZZU",
    "MAINSHIP",
    "MAIORA",
    "MAKO",
    "MALLARD",
    "MANGUSTA",
    "MANO MARINE",
    "MAREE HAUTE",
    "MARINELLO",
    "MARINER",
    "MARLIN MARINE",
    "MARQUIS",
    "MARSHALL",
    "MASTER",
    "MAXI YACHTS",
    "MAXUM",
    "MELGES",
    "MENORQUIN YACHTS",
    "MERY NAUTIC",
    "META",
    "MIMI",
    "MINGOLLA",
    "MOCHI CRAFT",
    "MOGGARO",
    "MONTE CARLO YACHTS",
    "MONTEREY",
    "MOODY",
    "MOSTES",
    "MYABCA",
    "NAJAD",
    "NAJADVARVET AB",
    "NARWHAL",
    "NAUTICAT",
    "NAUTIC SAINTONGE",
    "NAUTIQUE",
    "NAUTITECH",
    "NAUTOR",
    "NEEL",
    "NEPTUNE",
    "NEPTUNUS YACHTS",
    "NICOLS YACHT",
    "NIMBUS",
    "NORDIC TUG",
    "NORDKAPP",
    "NORD STAR",
    "NORTHSHORE YACHTS",
    "NORTHWIND",
    "NUOVA JOLLY",
    "OCCHILUPO YACHT & CARBON",
    "OCEAN STAR",
    "OCQUETEAU",
    "ORKNEY",
    "OUTREMER CATAMARANS",
    "OVERMARINE",
    "OYSTER MARINE",
    "PACIFIC CRAFT",
    "PARDO YACHTS",
    "PARKER",
    "PATRONE",
    "PEDRO BOATS",
    "PERFORMANCE",
    "PERSHING",
    "PIANTONI",
    "PIRELLI",
    "POGO",
    "PONCIN YACHTS",
    "PORTER AND HAYLETT",
    "PORTOFINO MARINE",
    "POSEIDON",
    "POSILLIPO",
    "POUVREAU",
    "PRESIDENT",
    "PRESTIGE",
    "PRINCESS",
    "PRIVILEGE MARINE",
    "PRUA AL VENTO",
    "PUMA",
    "PURSUIT",
    "PYXIS YACHT",
    "QUARKEN",
    "QUICKSILVER",
    "QUORNING BOATS",
    "RAFFAELLI",
    "RANCRAFT",
    "RAND BOATS",
    "RANIERI",
    "REGAL",
    "RHEA MARINE",
    "RIBEYE",
    "RIGIFLEX",
    "RINKER",
    "RIO",
    "RIVA",
    "RIVIERA",
    "RIZZARDI",
    "RM YACHTS",
    "ROBALO",
    "ROBERTSON AND CAINE",
    "RODMAN",
    "ROY FRANCK",
    "RPD",
    "RUBY YACHTS",
    "RYCH BOATS",
    "RYCK YACHTS",
    "SACS",
    "SACS MARINE",
    "SADLER",
    "SALONA YACHTS",
    "SALPA",
    "SAN LORENZO",
    "SARGO",
    "SARNICO",
    "SASGA",
    "SAVER",
    "SAXDOR",
    "SCARAB",
    "SCIALLINO",
    "SCIARELLI",
    "SCORPION",
    "SCOUT BOAT",
    "SEA DOO",
    "SEALINE",
    "SEALVER",
    "SEAMASTER",
    "SEA RAY",
    "SEGUE",
    "SELENE",
    "SELVA",
    "SESSA MARINE",
    "SETTE MARI",
    "SIGMA YACHTS",
    "SILCAR",
    "SILTALA YACHTS",
    "SILVERTON",
    "SIR",
    "SOLARIS",
    "SOLCIO BIONDI",
    "SOLEMAR",
    "SOTO",
    "SPARKMAN AND STEPHENS",
    "STARFISHER",
    "ST BOATS",
    "STINGRAY",
    "STOREBRO",
    "SUNREEF YACHTS",
    "SUNSEEKER",
    "SUR MARINE",
    "SWEDEN YACHTS",
    "TA CHIAO",
    "TECNOMAR",
    "TECNOMARINE",
    "TERHI",
    "TIARA",
    "TIGER MARINE",
    "TORNADO",
    "TRADER",
    "TRIDENT MARINE",
    "TRINTELLA",
    "TULLIO ABBATE",
    "ULTRAMAR",
    "UNIESSE MARINE",
    "VALIANT",
    "VANCOUVER",
    "VAN DE STADT",
    "VERSILCRAFT",
    "VIKING",
    "VIKO YACHTS",
    "VINDO",
    "VITECH",
    "WALLY YACHTS",
    "WARRIOR BOATS",
    "WAUQUIEZ",
    "WELLCRAFT",
    "WESTERLY MARINE",
    "WHALY",
    "WHITE SHARK",
    "WILLIAMS",
    "WILLIAMS JET TENDERS",
    "WINDY",
    "WRIGHTON",
    "X-YACHTS",
    "YACHTING FRANCE",
    "YAMAHA",
    "ZAR",
    "ZEPPELIN",
    "ZODIAC",
    "ZUANELLI"
  ];
}
